name: Build and Push Flink CDC Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Flink CDC Version'
        required: true
        default: '3.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
        
      - name: Build with Maven
        run: mvn clean install -DskipTests
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Create Pipeline Definition File
        run: |
          cat > pipeline-conf.yaml << 'EOF'
          # Example pipeline configuration
          pipeline:
            name: example-pipeline
            source:
              type: mysql
              jdbc-url: jdbc:mysql://mysql:3306/example
              username: ${MYSQL_USERNAME}
              password: ${MYSQL_PASSWORD}
              tables: ["example_table"]
            sink:
              type: kafka
              brokers: kafka:9092
              topic: example-topic
              format: json
          EOF
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./flink-cdc-dist/src/main/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/flink-cdc:${{ github.event.inputs.version || '3.0.0' }}
          build-args: |
            FLINK_CDC_VERSION=${{ github.event.inputs.version || '3.0.0' }}
            PIPELINE_DEFINITION_FILE=pipeline-conf.yaml